---
name: Runs linting and tests
on:
  workflow_call:

jobs:
  linting:
    runs-on: ubuntu-latest
    env:
      ENV: TESTING
      SECRET_KEY: secrets.SECRET_KEY
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: '3.10'
      - name: Install linters
        working-directory: .
        run: |
          python -m pip install --upgrade pip
          pip install -r dev-requirements.txt
      - name: Lint with flake8
        working-directory: .
        run: flake8 . --count --show-source --statistics
      - name: Check formatting with black
        working-directory: .
        run: black --check .
      - name: Run bandit
        working-directory: .
        run: bandit -c pyproject.toml -r .
      - name: Run type checking
        working-directory: .
        run: mypy .
      - name: Run HTML template linting
        working-directory: .
        run: djlint --lint .
  frontend-linting:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install npm packages
        working-directory: .
        run: npm ci
      - name: Lint JS & SCSS
        working-directory: .
        run: npm run check-all
      - name: run Lighthouse CI
        run: |
          npm install -g @lhci/cli@0.8.x
          lhci autorun
