name: Backup Environments
on:
  workflow_dispatch:

jobs:
  backup-environment:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        environment:
          - name: dev
          - name: staging
          - name: production
    steps:
      - name: output
        run: |
            echo "Environment is ${{ matrix.environment.name }}"

