name: Backup Environments
on:
  workflow_dispatch:

jobs:
  backup-environment:
    strategy:
      fail-fast: false
      matrix:
        environment:
          - name: dev
          - name: staging
          - name: production
    uses: ./.github/workflows/test-file.yml
    secrets: inherit
    with:
      environment: ${{ matrix.environment.name }}

