---
name: Tests for PRs
on:
  pull_request:
    branches:
      - main
      - prod
    paths:
      - '**'
      - '!docs/**'
      - 'docs/bpmn-workflow-models/**'
  workflow_dispatch: null

jobs:
  # Testing for all main and prod PRs
  test-and-lint:
    uses: ./.github/workflows/test.yml
    secrets: inherit
