---
name: Tests for PRs
on:
  pull_request:
    branches:
      - test
  workflow_dispatch:
  workflow_call:

jobs:
  scan-dev-pre-deploy:
    name: Zap scan of the dev site
    uses: ./.github/workflows/zap-scan.yml
    with:
        url: "https://fac-dev.app.cloud.gov/"
